export const GET_INFOS_REQUEST = "GET_INFOS_REQUEST";
export const GET_INFOS_SUCCESS = "GET_INFOS_SUCCESS";
export const GET_INFOS_FAIL = "GET_INFOS_FAIL";

export const GET_INFO_DETAILS_REQUEST = "GET_INFO_DETAILS_REQUEST";
export const GET_INFO_DETAILS_SUCCESS = "GET_INFO_DETAILS_SUCCESS";
export const GET_INFO_DETAILS_FAIL = "GET_INFO_DETAILS_FAIL";
export const GET_INFO_DETAILS_RESET = "GET_INFO_DETAILS_RESET";